<?php include('catalog-header.phtml') ?>

<div class="block">
    <div class="wrapper container">
        <div class="sidebar">
            <div class="widget catalog">
                <?php echo $this->catalogMenu() ?>
            </div>
        </div>
        <div class="content">
            <div class="products-list col-4">
                <?php echo $this->productsList($products, ['list' => 'List', 'cols' => 4]) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>

<?php if($category->get('text')) { ?>
<div class="block category-text">
    <div class="wrapper-narrow">
        <div class="std-text">
            <?php echo $category->get('text') ?>
        </div>
        <span class="show-all">Читать полностью...</span>
    </div>

    <script>
        $(function () {
            var box = $('.category-text');

            $('.show-all', box).on('click', function() {
                box.toggleClass('open');
            });
        });
    </script>
</div>
<?php } ?>