<?php include('catalog-header.phtml') ?>

<div class="block">
    <div class="wrapper container">
        <div class="sidebar">
            <div class="widget catalog">
                <?php echo $this->catalogMenu(['sub' => false]) ?>
            </div>
        </div>
        <div class="content">
            <?php echo $this->productsList($products, ['list' => 'list']) ?>
        </div>
        <div class="clear"></div>
    </div>
</div>