<div class="main-block-1">
    <div class="box">
        <div class="logo">MYPROTEIN</div>
        <div class="desc">
            Спортивное питание<br>из Великобритани
        </div>
    </div>
</div>
<div class="block">
    <div class="main-block-2">
        <div class="box">
            <a href="/about/" class="item">
                О бренде Myprotein
            </a>
            <a href="/delivery/" class="item">
                Доставки и точки выдачи
            </a>
        </div>
    </div>

    <div class="main-block-3">
        <?php
        $html =
            '<div class="catalog-list">';

        foreach (\Catalog\Model\Catalog::getEntityCollection() as $category) {
            $html .=
                '<a href="' . $category->getUrl() . '">' . $category->get('name') . '</a>';
        }

        $html .=
            '</div>';

        echo $html;
        ?>
    </div>

    <h2 class="header">Хиты продаж</h2>

    <?php echo $this->mobileProductsList($products) ?>
</div>