<a class="block-header" href="/">
    <div class="back"></div>
    <h1><?php echo $header ?></h1>
</a>

<div class="block">
    <?php
    $html =
        '<div class="catalog-list">';

    foreach (\Catalog\Model\Catalog::getEntityCollection() as $category) {
        $html .=
            '<a href="' . $category->getUrl() . '">' . $category->get('name') . '</a>';
    }

    $html .=
        '</div>';

    echo $html;
    ?>

    <?php echo $this->mobileProductsList($products, ['list' => 'list']) ?>
</div>
