<?php
$this->generateMeta(true);

$this->headLink()
    ->prependStylesheet(\Aptero\Compressor\Compressor::getPublicLink('css', 'mobile'))
    ->prependStylesheet('//use.fontawesome.com/releases/v5.4.1/css/all.css');

$this->headScript()
    ->prependFile(\Aptero\Compressor\Compressor::getPublicLink('js', 'mobile'))
    ->prependFile('/js/counters.js')
    ->prependFile('https://www.googletagmanager.com/gtag/js?id=UA-121245947-1')

    //->prependFile('/engine/js/jquery/jquery-ui.js')
    //->prependFile('/engine/js/jquery/jquery.js')

    ->prependFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php
        echo $this->headTitle() . "\n";
        echo $this->headMeta()  . "\n";
        echo $this->headLink()  . "\n";
        echo $this->headScript()  . "\n";
        echo $this->settings->get('html_head')
        ?>
    </head>
</head>
<body>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KB83CWB" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<div id="fog"></div>
<div id="header">
    <span class="item search"></span>
    <a href="/" class="item logo"></a>
    <a href="/user/" class="item user popup"></a>
    <a href="/cart/" class="item cart">
        <div class="counter"></div>
    </a>
    <div class="nav">
        <div class="trigger">
            <div class="icon">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="outer">
            <div class="shadow"></div>
            <div class="box">
                <?php /*<div class="search" >
                    <input class="query" placeholder="Поиск">
                </div>*/ ?>

                <ul class="menu">
                    <li><a href="/delivery/">Оплата и доставка</a></li>
                    <li><a href="/about/">О компании</a></li>
                    <li class="title">Каталог</li>

                    <?php
                    $сatalog = \Catalog\Model\Catalog::getEntityCollection();
                    echo $this->mobileCatalogMenu(['ul' => false, 'catalog' => $сatalog]);
                    ?>
                </ul>

                <div class="contacts">
                    <div class="row">
                        <a href="<?php echo $this->link($contacts->get('email')) ?>"><i class="far fa-envelope"></i> <?php echo $contacts->get('email') ?></a>
                    </div>
                    <div class="row">
                        <a href="<?php echo $this->link($contacts->get('phone_1')) ?>"><i class="fa fa-phone"></i> <?php echo $contacts->get('phone_1') ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php /*
    <div class="box menu">
        <ul>
            <li class="spec"><a href="/order/order-status/" class="popup">Что с моим заказом?</a></li>
            <li class="spec"><a href="/delivery/">Доставка и точки выдачи</a></li>
            <li class="spec"><a href="/about/">О бренде Myprotein</a></li>
            <?php echo $this->catalogMenu(['ul' => false, 'sub' => false]) ?>
            <li class="spec"><a href="/blog/">Блог</a></li>
        </ul>
    </div>

    <div class="box search">
        <form>
            <input name="query" placeholder="Поиск" class="std-input query">
            <button type="submit" class="sbm"><i class="fas fa-search"></i></button>
        </form>
    </div>
 */ ?>
</div>
<div id="search">
    <input type="text" placeholder="Поиск" class="search-ac">
    <div class="list">

    </div>
</div>

<div id="container">