<?php echo $this->header() ?>

<div class="block">
    <div class="wrapper">
        <div class="company-info">
            <div class="title">Контакты:</div>
            <div class="row">+7 (952) 388 58 85</div>
            <div class="row">info@myprotein.spb.ru</div>
            
            <div class="title">Реквизиты:</div>
            <div class="row">ИП Кукин Роман Олегович</div>
            <div class="row">ОГРНИП 317784700234399</div>
            <div class="row">ИНН 780728152802</div>
            <div class="row">ОКПО 0119699621</div>
        </div>
    </div>
</div>

<style>
    .company-info .title {
        font-size: 16px;
        font-weight: 600;
        text-transform: uppercase;
        margin-bottom: 8px;
        margin-top: 20px;
    }

    .company-info {
        margin-bottom: 2px;
        font-size: 14px;
    }
</style>