<?php include ('header.phtml'); ?>
<?php echo $content; ?>

<div class="block header-box">
    <div class="wrapper">
        <?php echo $this->breadcrumbs($breadcrumbs, array('delimiter' => ' → ', 'showLast' => false)) ?>
        <h1><?php echo $this->header ?></h1>
    </div>
</div>

<div class="block std-text">
    <div class="wrapper">
        <?php echo $this->textBlock($page->get('text')); ?>
    </div>
</div>

<?php include ('footer.phtml'); ?>