<?php /*
<script src="http://messanger/js/compiled/chat_popup.js"></script>
<script>Mibew.ChatPopup.init({"id":"5741f27436902aab","url":"http://messanger/chat?locale=ru","preferIFrame":true,"modSecurity":false,"width":640,"height":480,"resizable":true,"styleLoader":"http://messanger/chat/style/popup"});</script>
<a href="http://messanger//chat?locale=ru" target="_blank" onclick="Mibew.Objects.ChatPopups['5741f27436902aab'].open();return false;">Открыть</a>
*/ ?>

<?php include ('header.phtml'); ?>
<?php echo $content; ?>
<?php include ('footer.phtml'); ?>
