<h1>
    <i class="fas module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="text">Описание</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('image-image'));
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('url'));
                ?>
            </div>
            <div class="tab" data-tab="text">
                <?php echo $this->formRow($form->get('text')); ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fas fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fas fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fas fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<script>
$(function() {
    $('input[name="price_dollar"]').on('keyup', function () {
        var price = parseInt(parseInt($(this).val()) * 56.86);
        price = price ? price : 0;
        $('input[name="price_opt"]').val(price);
    });

    $('input[name="price_yuan"]').on('keyup', function () {
        var price = parseInt(parseInt($(this).val()) * 9.1);
        price = price ? price : 0;
        $('input[name="price_opt"]').val(price);
    });
});
</script>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fas fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fas fa-times"></i> Отмена</a>
</div>