<?php echo $this->header(array('type' => 'mobile')) ?>

<div class="about-view">
    <div class="block">
        <div class="wrapper">
            <div class="video">
                <div class="iframe-box">
                    <iframe src="https://www.youtube.com/embed/uYIdeNoMLqs" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>

    <div class="block info-block b1">
        <div class="wrapper">
            <div class="info">
                <div class="title">Производство мирового класса</div>
                <div class="desc">
                    <p>Все оборудование в компании Myprotein разработано под заказ, для обеспечения стабильности,
                        качество и максимальной скорости произведтсводства.<p>
                    <p>Британский консорциум розничной торговли сертифицировал продукцию Myprotein оценкой А по
                        безопасности пищевых продуктов, и на момент написания это один из немногих брендов спортивного
                        питания в Европе, получивший такую печать качества.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="block cols">
        <div class="wrapper">
            <div class="col">
                <img src="/images/about/brc.jpg" alt="">
                <div class="title">BRC</div>
                <div class="desc">
                    Myprotein первый и единственный бренд спортивного питания, получивший рейтинг A по безопасти
                    пищевой продукции.
                </div>
            </div>
            <div class="col">
                <img src="/images/about/labdor.jpg" alt="">
                <div class="title">Доказанное качество</div>
                <div class="desc">
                    Продукция стабильно получает 1 места по качеству и стоимости, от независимых тестировщиков - LabDoor.
                </div>
            </div>
            <div class="col">
                <img src="/images/about/infosport.jpg" alt="">
                <div class="title">Для профессионалов</div>
                <div class="desc">
                    Тесное сотрудничество с Informed Sport и WADA (World Anti-Doping Agency) дает возможность использовать продукцию myprotein
                    профессиональными спортсменами.
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    <div class="block info-block b2">
        <div class="wrapper">
            <div class="info">
                <div class="title">Контроль качества</div>
                <div class="desc">
                    <p>Myprotein проводит контроль качества на местах, на протяжении всего производственного процесса,
                        чтобы производит продукцию лучшими в Европе качества. В рамках этого
                        тестирования проводиться проверка всех партий сырья при поступлении на фабрику и инфракрасное
                        сканирование при отправке с завода покупателям.</p>
                    <p>Самостоятельно аудит и проверка с третьей стороны, идет сверх нормативных требований и GMP (Good
                        Manufacturing Practices), демонстрируя приверженность Myprotein дальнейшему повышению качества и
                        как следствие приносит пользу клиентам.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="block cols">
        <div class="wrapper">
            <div class="col">
                <img src="/images/about/fsa.jpg" alt="">
                <div class="title">Гигиена на 5</div>
                <div class="desc">
                    Myprotein уделяет особое внимание гигиене на производстве и как следствие получила максимальную
                    оценку от FSA(Food Standards Agency).
                </div>
            </div>
            <div class="col">
                <img src="/images/about/iso9001.jpg" alt="">
                <div class="title">ISO 9001 Аккредитация</div>
                <div class="desc">
                    Аккредитация ISO 9001 указывает, что Myprotein имеет самые высокие стандарты управления качеством
                    на производстве, что является еще одной причиной, производства продукции самого
                    высокого качества.
                </div>
            </div>
            <div class="col">
                <img src="/images/about/essna.jpg" alt="">
                <div class="title">ESSNA</div>
                <div class="desc">
                    Myprotein является членом Европейского Альянса Специалистов Спортивного Питания (ESSNA),
                    общеевропейской торговой ассоциации ведущих, созданной для обмена опытом, контролем качества
                    и целью вызова доверия у покупателей.
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    <div class="block info-block b3">
        <div class="wrapper">
            <div class="info">
                <div class="title">Проверка вкуса и запаха</div>
                <div class="desc">
                    <p>Электронный язык и нос машины позволяет производственной линии автоматически проводить оценку
                        вкуса жидких или твердых продуктов, растворенных в воде, аналогично человеческому языку или носу.</p>
                    <p>Электронные датчики определяют полный вкусовой профиль любого продукта. Эта передовая технология дает
                        вам уверенность, что каждый продукт Myprotein, что вы покупаете был тщательно проверен на
                        качество, вкус, и аромат и являются продукцией высокого качества.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="block cols">
        <div class="wrapper">
            <div class="col">
                <img src="/images/about/als.jpg" alt="">
                <div class="title">ALS</div>
                <div class="desc">
                    ALS - являются независимыми представителями UKAS (Сервис аккредитации Великобритании) и следят
                    за соблюдением ISO17025 и служат еще одним подтверждением качества продукции Myprotein.
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>