<?php /*
$color1 = $discount->get('color');
$color2 = $color1 == '000000' ? 'ffffff' : '000000';
$btnStyle = 'style="background-color: #' . $color1 . '; color: #' . $color2 . '"';
?>

<a href="/catalog/?sort=discount&direct=down" class="main-slider" style="background-image: url(<?php echo $discount->getPlugin('image')->getImage('m') ?>)">
    <div class="box <?php echo $discount->get('shape') ?>" style="background-color: #<?php echo $discount->get('background') ?>; color: #<?php echo $color1 ?>">
        <div class="inner" style="border-color: #<?php echo $discount->get('border') ?>;">
            <?php //<div class="header r1">скидки</div> ?>
            <div class="header r2">Скидки</div>
            <div class="discount">
                <span class="bf">до</span>
                <span class="percent"><?php echo $discount->get('discount') ?></span>
                <span class="af">%</span>
            </div>
            <div class="btn" <?php echo $btnStyle ?>>Выбрать</div>
        </div>
    </div>
</a>
*/ ?>
<a href="/catalog/" class="main-block-1">
    <div class="shadow"></div>
    <div class="info">
        <div class="logo">Myprotein</div>
        <div class="text">
            Спортивное питание из Великобритании
        </div>
        <div class="btns">
            <div class="btn c2">Открыть каталог</div>
        </div>
    </div>
    <div class="video">
        <img src="images/placeholder.jpg" alt="" class="placeholder-image">
    </div>
</a>

<script>
    <?php
    $settings = \Application\Model\Settings::getInstance();
    $video = '5fSt97d20Lw';
    ?>

    var block = $('.main-block-1');
    var video = $('.video', block);

    var marginTop = ((block.innerWidth() * 0.5625) - block.innerHeight()) / 2;

    video.YTPlayer({
        fitToBackground: true,
        controls: 0,
        videoId: '<?php echo $video ?>',
        pauseOnScroll: false,
        playerVars: {
            start: 0,
            autoplay: 1,
            controls: 0,
            showinfo: 0
        },
        callback: function() {
            video.children('.background').css({marginTop: -marginTop});
        }
    });
</script>

<?php/*
$products = \Catalog\Model\Product::getEntityCollection();
$products->select()
    ->limit(4)
    ->order('popularity DESC');*/


?>

<div class="main-block-2">
    <div class="wrapper-narrow cols">
        <div class="col-50 products-list col-2">
            <?php echo $this->productsList($products1); ?>
        </div>
        <div class="col-50 products-list col-1">
            <?php echo $this->productsList($products2, 1); ?>
        </div>
    </div>
</div>

<div class="main-block-3">
    <div class="wrapper-narrow">
        <div class="info">
            <div class="title">Доставка по всей Росии</div>

            <div class="row">
                <b>620</b> городов
            </div>
            <div class="row">
                <b>3000</b> пунктов выдачи
            </div>

            <div class="btn c2">Узнать подробнее</div>
        </div>
    </div>
</div>

<div class="main-block-2">
    <div class="wrapper-narrow cols">
        <div class="col-50 products-list col-1">
            <?php echo $this->productsList($products3, 1); ?>
        </div>
        <div class="col-50 products-list col-2">
            <?php echo $this->productsList($products4); ?>
        </div>
    </div>
</div>

<div class="main-block-2">
    <div class="wrapper-narrow cols">
        <div class="col-50 products-list col-2">
            <?php echo $this->productsList($products6); ?>
        </div>
        <div class="col-50 products-list col-1">
            <?php echo $this->productsList($products5, 1); ?>
        </div>
    </div>
</div>

<style>
    .main-block-2 .wrapper {
        max-width: 1100px;
    }

    .main-block-2 .col-50 {
        padding: 0;
    }

    .products-list .pic {
        text-align: center;
        padding: 15px;
    }

    .products-list .pic .img-box {
        max-height: 175px;
        text-align: center;
    }

    .main-block-2 .products-list .info {
        background: none;
        padding-top: 0;
        box-shadow: none;
    }

    .main-block-2 .product .desc {
        height: 15px;
    }

    .main-block-2 .products-list.col-2 .product {
        flex: 0 0 calc(50% - 8px);
        margin: 0 4px 8px 4px;
    }

    .main-block-2 .products-list.col-1 .product {
        flex: 0 0 100%;
        margin-bottom: 8px;
    }

    .main-block-2 .cols > .col-1 {
        padding-right: 8px;
    }

    .main-block-2 .products-list.col-1 .product .title{
        font-size: 22px;
        font-weight: 400;
    }

    .main-block-2 .products-list.col-1 .price-box {
        width: 140px;
        padding-top: 0;
    }

    .main-block-2 .products-list.col-1 .price-box .price {
        font-size: 35px;
    }

    .main-block-2 .products-list.col-1 .price-box .price-old {
        font-size: 16px;
    }

    .main-block-2 .products-list.col-1 .desc {
        margin-top: 10px;
    }

    .main-block-2 .products-list.col-1 .pic .img-box {
        width: 400px;
    }

    .main-block-2 .products-list.col-1 .pic img {
        max-height: none;
    }

    .main-block-2 .products-list.col-1 .pic .img-box {
        max-height: 454px;
    }

    .main-block-2 .products-list.col-1 .pic {
        text-align: center;
        padding: 30px 20px 20px 20px;
    }

    .main-block-2 .products-list.col-1 .order-box {
        max-width: 300px;
        margin: 20px auto 0 auto;
    }

    .main-block-2 .products-list.col-1 .order-box .btn {
        height: 40px;
        line-height: 40px;
        width: 125px;
        font-size: 16px;
        margin-top: 4px;
    }

    .main-block-2 .products-list.col-1 .pic .events .discount i {
        font-size: 28px;
    }

    .main-block-2 .products-list.col-1 .pic .events .discount {
        height: 40px;
        line-height: 40px;
        padding: 0 9px;
        font-size: 31px;
    }
</style>

<?php /*
<a href="/catalog/?sort=discount&direct=down" class="main-slider" style="background-image: url(<?php echo $discount->getPlugin('image')->getImage('m') ?>)">
    <div class="box <?php echo $discount->get('shape') ?>" style="background-color: #<?php echo $discount->get('background') ?>; color: #<?php echo $color1 ?>">
        <div class="inner" style="border-color: #<?php echo $discount->get('border') ?>;">
            <?php //<div class="header r1">скидки</div> ?>
            <div class="header r2"><?php echo $discount->get('name') ?></div>
            <div class="discount">
                <span class="bf">до</span>
                <span class="percent"><?php echo $discount->get('discount') ?></span>
                <span class="af">%</span>
            </div>
            <div class="btn" <?php echo $btnStyle ?>>Выбрать</div>

            <div class="counter">
                <div class="tm days" <?php echo $btnStyle ?>></div>
                <div class="tm hours" <?php echo $btnStyle ?>></div>
                <div class="tm min" <?php echo $btnStyle ?>></div>
                <div class="tm sec" <?php echo $btnStyle ?>></div>
            </div>
        </div>
    </div>
</a>

<script type="text/javascript">
    var counter = $('.main-slider .counter');
    var date = '<?php echo str_replace('-', '/', $discount->get('date_to')); ?>';

    $('.days', counter).countdown(date, function(event) {
        $(this).html(event.strftime('<div>%-D</div> дней'));
    });

    $('.hours', counter).countdown(date, function(event) {
        $(this).html(event.strftime('<div>%-H</div> часов'));
    });

    $('.min', counter).countdown(date, function(event) {
        $(this).html(event.strftime('<div>%-M</div> минут'));
    });

    $('.sec', counter).countdown(date, function(event) {
        $(this).html(event.strftime('<div>%-S</div> сек'));
    });
</script>
*/ ?>
<?php /*
<div class="block">
    <div class="wrapper">
        <div class="banners-list cols">
            <div class="col-66">
                <div class="cols">
                    <div class="col-50">
                        <a href="/about/" class="banner">
                            <img src="/images/banners/1.jpg" alt="">
                        </a>
                    </div>
                    <div class="col-50">
                        <span class="banner">
                            <img src="/images/banners/2.jpg" alt="">
                        </span>
                    </div>
                </div>
                <div class="cols">
                    <div class="col-100">
                        <a href="/delivery/" class="banner">
                            <img src="/images/banners/3.jpg" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-33">
                <div class="products-banner">
                    <div class="header">
                        Лидеры продаж
                    </div>

                    <div class="list">
                        <?php
                        foreach ($products as $product) {
                        echo
                            '<a href="' . $product->getUrl() . '" class="item pr-link product" data-id="' . $product->getId() . '" data-list="Main page">'
                                .'<div class="pic">'
                                    .'<img src="' . $product->getPlugin('image')->getImage('s') . '" alt="' . $product->get('name') . '">'
                                .'</div>'
                                .'<div class="title">' . $product->get('name') . '</div>'
                                . $this->stars($product->get('stars'))
                            .'</a>';
                        } ?>
                        <?php for($i = 0; $i < 6; $i++) { ?>

                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div class="block blog-list main">
    <div class="wrapper">
        <div class="header">
            <h2>Последнее в блоге</h2>
            <a href="/blog/">Показать все статьи</a>
        </div>
        <div>
            <?php echo $this->articlesList($articles) ?>
            <div class="clear"></div>
        </div>
    </div>
</div>
*/ ?>