<div class="opt-view">
    <div class="block dynamics-block">
        <div class="wrapper">
            <div class="block-header">
                <h2>Динамика продаж в Росии</h2>
                <div class="desc">Myprotein являеться самым быстрорастущим брендом спортивного питания в России и мире.</div>
            </div>

            <div class="cols">
                <div class="col google">
                    <div class="title">
                        <img src="/images/opt/google.jpg" alt="">
                    </div>
                    <div class="desc">Сравнение популяронсти Myprotein (красный) и Optimum Nutrition (синий) в Google
                        Trends по России за поледние 5 лет</div>

                    <a href="https://trends.google.ru/trends/explore?date=today%205-y&geo=RU&q=Optimum%20Nutrition,Myprotein" target="_blank">
                        <img src="/images/opt/gtrends.png" alt="Google Trends">
                    </a>
                </div>
                <div class="col yandex">
                    <div class="title">
                        <img src="/images/opt/yandex.jpg" alt="">
                    </div>
                    <div class="desc">
                        Топ брендов по запросам в поиске по данным wordstat.yandex.ru по России за июнь 2018 года.
                        (Кол-во запросов с название бренда в месяц)
                    </div>

                    <div class="table">
                        <div class="row">
                            <div class="key">Optimum Nutrition</div>
                            21 122
                        </div>
                        <div class="row mp">
                            <div class="key">Myprotein</div>
                            14 074
                        </div>
                        <div class="row">
                            <div class="key">VPlab</div>
                            13 760
                        </div>
                        <div class="row">
                            <div class="key">Power System</div>
                            12 644
                        </div>
                        <div class="row">
                            <div class="key">Ultimate Nutrition</div>
                            11 302
                        </div>
                        <div class="row">
                            <div class="key">Scitec</div>
                            7 602
                        </div>
                        <div class="row">
                            <div class="key">RLine</div>
                            5 160
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>


    <div class="block quality-block">
        <div class="wrapper">
            <div class="block-header">
                <h2>Качеcтво</h2>
                <div class="desc">Мы получаем товары напрямую от производителя в Великбитании без посредников,
                    поэтому вы можете быть уверены в качество продоваемого спортивного питания.</div>
            </div>

            <div class="cols">
                <div class="col">
                    <iframe width="100%" height="315" src="https://www.youtube.com/embed/eHh8f4XgHUw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <div class="col">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/eHh8f4XgHUw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<style>
    .opt-view .block-header {
        text-align: center;
        margin-bottom: 45px;
    }

    .opt-view .block-header h2 {
        font-size: 33px;
        font-weight: bold;
        padding-top: 45px;
        text-transform: none;
        margin: 0 0 8px 0;
    }

    .opt-view .block-header .desc {
        font-size: 17px;
        max-width: 900px;
        margin: 0 auto;
    }

    .opt-view .dynamics-block .col {
        width: 49%;
        float: left;
    }

    .opt-view .dynamics-block .title {
        margin-bottom: 5px;
    }

    .opt-view .dynamics-block .col .desc {
        margin-bottom: 24px;
        max-width: 500px;
    }

    .opt-view .dynamics-block .google {
        margin-right: 2%;
        margin-left: 6%;
    }

    .opt-view .dynamics-block .yandex {
        width: 43%;
    }

    .opt-view .dynamics-block .table {
        max-width: 400px;
    }

    .opt-view .dynamics-block .table .row {
        position: relative;
        font-size: 15px;
        padding: 4px 10px;
        text-align: right;
        margin-bottom: 3px;
    }

    .opt-view .dynamics-block .table .row.mp {
        color: #1a5bc4;
        font-weight: bold;
    }

    .opt-view .dynamics-block .table .row:nth-child(2n) {
        background: #e4e4e4;
    }

    .opt-view .dynamics-block .table .key {
        position: absolute;
        top: 4px;
        left: 10px;
        text-align: left;
        font-weight: bold;
    }

    .opt-view .quality-block {
        background: #f4f4f4;
    }

    .opt-view .quality-block .col {
        width: 49%;
        margin-left: 2%;
        float: left;
    }

    .opt-view .quality-block .col:first-child {
        margin-left: 0;
    }

    .opt-view .quality-block {

    }

    .opt-view .quality-block {

    }

    .opt-view {

    }

    .opt-view {

    }
</style>